data:
  path: '../../src/data/dataset/dp_long.npz'
  n_samples: 420
  n_steps: 1501
  delay: 0 # 0 for no delay
  double_precision: false

scaling:
  mode: "none"

weak_form:
  enabled: true
  parameters: [13, 2, 2, 2]  # example values; adjust as needed

split:
  train_frac: 0.75

dataloader:
  batch_size: 32
  
model:
  name: 'double_pendulum_wmlp'
  type: "NN"   # Options: "NN", "LSTM", "GNN"
  encoder_layers: 1
  processor_layers: 1
  decoder_layers: 1
  latent_dimension: 32

training:
  n_epochs: 5000
  save_interval: 1
  load_checkpoint: true