data:
  path: '../../src/data/dataset/dp_long.npz'
  n_samples: 100
  n_steps: 1001
  delay: 0 # 0 for no delay

scaling:
  mode: "01"
  load_from_checkpoint: None

weak_form:
  enabled: True
  parameters: [11, 2, 3, 2, 0.5]  # example values; adjust as needed

split:
  train_frac: 0.75

dataloader:
  batch_size: 32
  

model:
  model_type: "NN"   # Options: "NN", "LSTM", "GNN"
  encoder_layers: 1
  processor_layers: 1
  decoder_layers: 1
  latent_dimension: 32